[Issue-7] PageFooter and PageHeader generation
igumnoff/shiva pull request #11
Opened 2024-04-19 17:28 UTC by ScriptHound

added generation of a page_header and page_footer for text

2024-04-19 19:00 UTC, evgenyigumnov commented on lib/src/text.rs
> +        for element in &document.page_header {
покройте тестами свое решение

2024-04-19 19:01 UTC, evgenyigumnov requested changes
resolve my comments please

2024-04-20 09:10 UTC, ScriptHound commented
Tests were added but rather visual. And im still hesitating what PageFooter and PageHeader should look like but now the whole document looks like

`my header string

First header 
  
 1. List item 1 
 2. List item 2 
 3. List item 3 
  
 Paragraph  bla bla bla blabla bla bla blabla bla bla blabla bla bla blabla bla bla blabla bla bla blabla bla bla blabla bla bla blabla bla bla 
 blabla bla bla blabla bla bla blabla bla bla blabla bla bla bla 
  
 Second header 
  
 +-----------------+-----------------+ 
 | Header 1        | Header 2        | 
 +-----------------+-----------------+ 
 | Row 1, Column 1 | Row 1, Column 2 | 
 | Row 2, Column 1 | Row 2, Column 2 | 
 +-----------------+-----------------+ 
 

my footer string
`

2024-04-20 09:53 UTC, evgenyigumnov approved these changes
Ok, thanks

2024-04-20 09:53 UTC, merged