SHIVA: generate list for pdf
igumnoff/shiva pull request #9
Opened 2024-04-19 13:10 UTC by Longlom

2024-04-19 18:15 UTC, evgenyigumnov commented on lib/src/lib.rs
> -#![doc = include_str!("../README.md")]
верните назад пожалуйста

#![doc = include_str!("../[README.md](https://readme.md/)")]

потому что [crates.io](https://crates.io/) и [docs.io](https://docs.io/) работают если такой путь

2024-04-19 18:22 UTC, evgenyigumnov commented on lib/src/pdf.rs
> +    #[test]
сейчас
```
0 List item 1
1 List item 2
2 List item 3
0 List item secode level 1
1 List item secode level 2
4 List item 4
0 List item secode level 3
1 List item secode level 4
6 List item 5
0 List item secode level 5
```
а нужно
![Screenshot 2024-04-19 232212](https://github.com/igumnoff/shiva/assets/10693931/86d51336-617a-4717-bcf1-17c44cbfe4fe)

2024-04-19 18:59 UTC, evgenyigumnov requested changes
check my comments please

2024-04-19 19:45 UTC, Longlom commented
Еще не готово. Почему-то значки символов кроме залитого круга не рендерятся. Буду исследовать пока почему

2024-04-20 05:57 UTC, evgenyigumnov commented on lib/src/pdf.rs
> -                                item_text = index.to_string();
![image](https://github.com/igumnoff/shiva/assets/10693931/a5a95efa-b8c3-4d78-8654-674e6dbff30b)

![Screenshot 2024-04-19 232212](https://github.com/igumnoff/shiva/assets/10693931/1c91d768-e11b-4be2-8ed7-7907c7c91e95)

2024-04-20 06:00 UTC, evgenyigumnov commented
check README.md file please

![image](https://github.com/igumnoff/shiva/assets/10693931/e6c022ff-8350-4de6-94bc-cdfa4ecda45a)

Add PLUS to LIST column

2024-04-20 17:21 UTC, Longlom commented
Instead of circle added Stroked rectangle

2024-04-20 17:43 UTC, merged